### ISSUE TITLE
unexpected exit code for resty

### ISSUE THREAD

**Issue by saks** [openresty/resty-cli#21]
I found that when nginx crashes with `SIGSEGV`, resty will exit with status `0`.
```sh
root@abb1f2c5696e:/app# cat > /tmp/1.lua
local ffi = require 'ffi'
ffi.cdef 'void* malloc(size_t bytes);'
ffi.fill(ffi.C.malloc(0), 999999999999999999999999)
root@abb1f2c5696e:/app# /app/bin/resty /tmp/1.lua
root@abb1f2c5696e:/app# echo $?
0
root@abb1f2c5696e:/app# luajit /tmp/1.lua
Segmentation fault (core dumped)
root@abb1f2c5696e:/app# echo $?
139
```
Is it expected behavior?

**Comment by ghprince** [comment]
+1, similar frustration here.

```
# resty -e 'ngx.sleep(60) print("done\n")'
<Hit Ctrl-C here>
# echo $?
0
```

Is it expected behavior?


also if I file up this in one terminal
```
# resty -e 'ngx.sleep(60) print("nginx done\n")'
```

and on another terminal
```
# ps -ef | grep nginx
root        34     1  0 12:06 ?        00:00:00 perl /opt/openresty/bin/resty -e ngx.sleep(60) print("nginx done\n")
root        35    34  0 12:06 ?        00:00:00 nginx -p /tmp/2WLBZMQnQ4/ -c conf/nginx.conf
root        39    13  0 12:06 ?        00:00:00 grep nginx
```

If I `kill` the perl process, the first terminal gives
```
Terminated
# echo $?
143
```

If I `kill` the nginx process, the first terminal gives
```
# echo $?
0
```

I think basically the question is why do we need to bit-shift [here](https://github.com/openresty/resty-cli/blob/master/bin/resty#L419)?

**Comment by agentzh** [comment]
@saks @ghprince Mind to propose a pull request for this? Thanks!

**Comment by agentzh** [comment]
@saks @ghprince Never mind, I've just committed fixes to the git master branch. Please try it out. Thank you!
