### ISSUE TITLE
resty doesn't print output of global variable defined with load

### ISSUE THREAD

**Issue by bungle** [openresty/resty-cli#26]
This doesn't work as expected:

```lua
resty -e "load 'a = 3'(); print(a)"
```

**OR**

a.lua:

```lua
load "a = 3"()
print(a)
```

and

```lua
resty a.lua
```

**Prints:** `nil`
**Expected:** `3`

**Comment by agentzh** [comment]
@bungle I think this is because in OpenResty, the main light thread uses its own global variable environment and the `load` builtin is just not aware of that. A workaround is to use `_G` explicitly in the load string:

```console
$ resty -e "load '_G.a = 3'(); print(a)"
3
```

But I think the documentation already says uses of Lua global variables is a bad idea? ;)

**Comment by bungle** [comment]
Well, it wasn't originally my problem. I tried to run `Penlight` test-suite, and it failed with `resty`, so I just reported this in hopes that there could be an easy fix for that. If not, you may close this.

**Comment by agentzh** [comment]
Gotcha. AFAIK, there's no easy fix for this. I'm closing it.
